export enum SurveyOption {
  ADVERTISING_VK = "ADVERTISING_VK",
  FRIENDS_TOLD = "FRIENDS_TOLD",
  APPLE_STORE = "APPLE_STORE",
  GOOGLE_PLAY = "GOOGLE_PLAY",
  SITE_OR_SEARCH = "SITE_OR_SEARCH",
  INSTAGRAM = "INSTAGRAM",
  OTHER = "OTHER"
}
