export enum BreadCrumbDescription {
  SEL_SELECTED_CITY_TASKS='SEL_SELECTED_CITY_TASKS',
  SEL_ACTIVE_CATEGORIES_TASKS='SEL_ACTIVE_CATEGORIES_TASKS',
  SEL_SELECTED_TASKS='SEL_SELECTED_TASKS',

  SEL_SELECTED_CITY_PERFORMERS='SEL_SELECTED_CITY_PERFORMERS',
  SEL_ACTIVE_CATEGORIES_PERFORMERS='SEL_ACTIVE_CATEGORIES_PERFORMERS',
}
