export enum TypeBlocking {
    THREE_DAYS = 'THREE_DAYS',
    SEVEN_DAYS = 'SEVEN_DAYS',
    FOURTEEN_DAYS = "FOURTEEN_DAYS",
    THIRTY_DAYS = 'THIRTY_DAYS',
    NINETY_DAYS = "NINETY_DAYS",

    THREE_DAYS_FOR_PARTNER = "THREE_DAYS_FOR_PARTNER",
    SEVEN_DAYS_FOR_PARTNER = "SEVEN_DAYS_FOR_PARTNER"
}