export const FAQ = {
    whatIsGoodDeal:
        '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">Здравствуйте, уважаемый пользователь!</span></p>' +
        '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">Если Вас интересует данный вопрос, значит, вероятнее всего, Вы только начинаете знакомство с нашим сервисом! Мы очень рады, что Вас заинтересовала наша интернет-платформа!</span></p>' +
        '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">Что же такое </span><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;"><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;" lang="en-US">GoodDeal</span></span><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">? Это интернет-агрегатор, реализованный в виде мобильных приложений на платформах </span><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;"><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;" lang="en-US">IOS</span></span><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;"> и </span><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;"><span lang="en-US">Android</span></span><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;"> и сайта. Главная задача </span><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;"><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;" lang="en-US">GoodDeal</span></span><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;"> &ndash; свести между собой заказчика и исполнителя. Таким образом, </span><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;"><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;" lang="en-US"><strong>GoodDeal</strong></span></span><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;"><strong> &ndash; это площадка, с помощью которой</strong></span><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">:</span></p>' +
        '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">1. Пользователь может найти специалиста определённого профиля для выполнения определённых поручений, решения определённых задач и проблем;</span></p>' +
        '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">2. Можно найти курьера, бригаду грузчиков или исполнителя, который купит для Вас </span><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">все</span><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;"> необходимые товары и доставит по необходимому адресу;</span></p>' +
        '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">3. Даётся возможность подработать любому, при этом не обязательно иметь специализацию или образование! Достаточно иметь желание, свободное время и гаджет (планшет/смартфон);</span></p>' +
        '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">4. Специалист-исполнитель может найти себе больше клиентов и новых заданий.</span></p>' +
        '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">GoodDeal &ndash; это качественно! </span></p>' +
        '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;"><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;" lang="en-US">GoodDeal</span></span><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;"> &ndash; это прозрачно!</span></p>' +
        '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">GoodDeal &ndash; это быстро! </span></p>' +
        '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">GoodDeal &ndash; это современно и удобно! </span></p>' +
        '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">GoodDeal &ndash; это Безопасно! </span></p>',

    whyChooseGoodDeal:
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;"><span style="font-size: large;" lang="en-US">GoodDeal</span></span><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;"> &ndash; это удобный сервис, который поможет Вам найти специалистов различных профилей, даст возможность найти больше клиентов или просто заработать при наличии свободного времени и желания.</span></p>' +
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;"><strong>Почему Вам стоит выбрать именно наш сервис среди других?</strong></span></p>' +
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;"><span lang="en-US">GoodDeal</span></span><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">&ndash; это прозрачно!<br /> Мы работаем без скрытых комиссий. Мы не берем денег с пользователей за клики, за продвижение профиля или за возможность создать задание и поднятие его в топ. Мы берем лишь небольшой % с исполнителя по факту выполненного задания.</span></p>' +
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">GoodDeal &ndash; это качественно! <br /> Мы стараемся поощрять бонусами добросовестных исполнителей, а с недобросовестными прекращаем сотрудничество. </span></p>' +
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">GoodDeal &ndash; это быстро! <br /> Наш сервис даёт Вам возможность найти в кратчайшие сроки необходимого специалиста или новых клиентов, не выходя из дома.</span></p>' +
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">GoodDeal &ndash; это современно и удобно! <br /> Для решения большинства Ваших потребностей Вам потребуется только гаджет и наше приложение! </span></p>' +
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">GoodDeal &ndash; это Безопасно! <br /> Мы гарантируем исполнителям 100% оплату, а заказчикам возврат средств, в случае не выполненной услуги!</span></p>' +
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">При этом, Вам нужен будет лишь один аккаунт, с помощью которого Вы можете быть одновременно и исполнителем, и заказчиком!</span></p>',

    roleOfTheCustomerContractorInApplication:
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;"><strong>Заказчик</strong></span><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;"> &ndash; это человек, который ищет специалиста определённого профиля, бригаду грузчиков или ищет попутчика и т.д&hellip; Иными словами: Это человек, который заказывает услугу. </span></p>' +
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">В нашем приложении именно </span><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;"><u style="font-size: large;">заказчик формирует задание</u></span><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">, которое ему необходимо выполнить. Именно заказчик формирует параметры задания такими, какими он хочет видеть их</span><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;"><u>.</u></span></p>' +
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;"><strong>Исполнитель</strong></span><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;"> &ndash; это специалист определённого профиля; Человек, который хочет заработать на своих навыках, умениях; Человек, который хочет заработать при наличии свободного времени. Исполнителю не обязательно иметь навыки или образование для заработка, так как некоторые категории услуг этого не требуют.</span></p>' +
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">В приложении исполнитель </span><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;"><u>не создаёт задания</u></span><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">, а откликается на них. Исполнителю можно найти задания самому, или ждать, пока ему предложат их. Для того, чтобы исполнителю быстрее найти задание/чтобы заказчики его быстрее нашли, ему достаточно:</span></p>' +
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">1. В личном профиле максимально детально заполнить графы. Обратите особое внимание на графу &laquo;Обо мне&raquo;. Здесь нужно заполнить информацию о себе как об исполнителе: какими работами занимались, какой опыт в тех или иных работах имеете и т.д. (Писать желательно честно, просто и понятно). </span></p>' +
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">2. В разделе &laquo;Виды выполняемых работ&raquo; из выпадающего меню нужно выбрать категории и подкатегории услуг, в которых Вы работаете. Если таких категорий/подкатегорий Вы не нашли, то Вы можете выбрать наиболее близкие по смыслу, либо выбрать в той или иной категории подкатегорию &laquo;Другое&raquo;, а так же написать в техподдержку сообщение с предложением о внесении новых категорий/подкатегорий. Мы рассмотрим все предложения.</span></p>' +
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">Обратите внимание, что именно Ваш профиль и является чем-то вроде объявления о предоставляемых Вами услугах.</span></p>',

    howToBecomPerformer:
    '<a name="how-become-performer"></a>' +
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">Для того, чтобы стать исполнителем, достаточно быть зарегистрированным в нашем приложении/на нашем сайте и иметь телефон/планшет/компьютер. </span></p>' +
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">В браузерной версии приложения для того, чтобы стать исполнителем, Вам необходимо перейти в личный профиль. Далее в личном профиле переходите в раздел &laquo;Стать исполнителем&raquo; и потом нажимаете на кнопку &laquo;Стать Исполнителем&raquo;.</span></p>' +
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">В мобильном приложении (</span><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;"><span lang="en-US">IOS</span></span><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">, </span><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;"><span lang="en-US">Android</span></span><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">) в личном профиле Вам нужно перейти в Мои Задачи, далее зайти в раздел &laquo;Стать исполнителем&raquo; и нажать на кнопку &laquo;Стать Исполнителем&raquo;. Так же стать исполнителем можно перейдя в настройки приложения (знак в виде шестеренки в верхнем правом углу) и кликнув на функцию &laquo;Стать Исполнителем&raquo;.</span></p>' +
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">Далее, Вам нужно заполнить все поля Вашего личного профиля. Вы сделали все эти действия? Поздравляем! Теперь Вы &ndash; исполнитель! </span></p>' +
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">Как видите, это довольно просто. После этого Вы можете найти задания и связаться с заказчиком в интересующих Вас сферах деятельности, или заказчик сам свяжется с Вами и предложит вам задание.</span></p>' +
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">Далее, если исполнитель хочет взять задание, в котором предполагается расчёт </span><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;"><strong style="font-size: large;">обычным платежом</strong></span><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">, то в процессе взятия задания у исполнителя выйдет окошко с суммой. Эта сумма и будет являться комиссией. Для подачи заявки на выполнение и взятия задания исполнителю необходимо оплатить эту комиссию. Для уплаты комиссии необходимо будет нажать соответствующую кнопку и следовать дальнейшим инструкциям. Если выбрали другого исполнителя, а вы уже оплатили комиссию, то средства вернуться на ваш виртуальный счет и в дальнейшем Вы сможете использовать их для взятия других заданий.</span></p>' +
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;"><strong>При безопасном платеже </strong></span><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">комиссия изначально взимается с вознаграждения исполнителя и в этом случае стоимость заказа будет указана уже с вычетом комиссии.</span></p>' +
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">Так же, рекомендуем вам ознакомиться со следующими документами:</span></p>' +
    '<p><span style="color: #0000ff;"><u style="font-size: large;"><a href="/support/commission"><span style="color: #0000ff;font-family: Times New Roman, serif; font-size: large;">Условия формирования комиссии</span></a></u></span></p>',

    whatCommissionsAwaitMe:
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;"><span style="font-size: large;">Обращаем Ваше внимание на то, что в </span></span><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;"><span style="font-size: large;"><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;" lang="en-US">GoodDeal</span></span></span><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;"><span style="font-size: large;"> существует 2 комиссии, которые распространяются на исполнителей:</span></span></p>' +
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;"><span style="font-size: large;"><strong>Процент от сделки</strong></span></span><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;"><span style="font-size: large;">. </span></span><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;"><span style="font-size: large;"><span lang="en-US">GoodDeal</span></span></span><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;"><span style="font-size: large;"> берёт 7 процентов от сделки с обычным платежом, и 13 процентов от сделки с безопасным платежом. Мы берём % только от совершённых сделок. В случае с безопасным платежом исполнитель видит задание уже с итоговой стоимостью и вычтенной комиссией. При обычном платеже пользователь должен заплатить комиссию 7 % в момент подачи заявки на выполнение. Обратите внимание, что если для выполнения задания с обычным платежом выбрали другого исполнителя, уплаченные Вами 7 % вернутся Вам на виртуальный счёт и будут доступны для подачи заявок на выполнение других заданий. </span></span></p>' +
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;"><span style="font-size: large;"><strong> 60 рублей за выведение средств. </strong></span></span><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;"><span style="font-size: large;">Данная комиссия взимается платёжным сервисом &laquo;Единая касса&raquo; и взимается с тех средств, которые вы заработали в </span></span><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;"><span style="font-size: large;"><span lang="en-US">GoodDeal</span></span></span><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;"><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;"> и хотите вывести из сервиса. Обратите внимание, что сервису не важно, какую сумму вы хотите вывести, стоимость всегда остаётся 60 рублей. В связи с этим мы рекомендуем выводить средства, заработанные с нескольких заданий. В этом случае в сможете сэкономить на комиссии. Так же хотим уточнить, что в случае, если Вы будете выводить более 10&nbsp;000 рублей сразу, мы готовы уплатить комиссию за Вас.</span></span></p>' +
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;"><span style="font-size: large;">В отличие от наших конкурентов, мы используем более честный (на наш взгляд) подход по отношению к нашим исполнителям: мы не берём никаких денег за клики и отклики. Мы берём % только от совершённых сделок и даём возможность выводить средства более крупными суммами, экономя на комиссии.</span></span></p>',

    howToChooseReliableContractor:
    '<a name="reliable-performer"></a>' +
    '<p><span style="color: #444444; font-family: Times New Roman, serif;font-size: large;">Очень часто, работая с незнакомым исполнителем, заказчик задаётся вопросами: &laquo;Как выбрать надёжного исполнителя? Как не выбрать исполнителем мошенника? Как не быть обманутым?&raquo; И в данном разделе мы хотим Вам рассказать, как выбрать надёжного исполнителя.</span></p>' +
    '<p><span style="color: #444444; font-family: Times New Roman, serif;font-size: large;"><strong>Как выбрать надёжного исполнителя и не быть обманутым? Следует соблюдать следующие пункты:</strong></span></p>' +
    '<p><span style="color: #444444; font-family: Times New Roman, serif;font-size: large;">1. Наличие значка &laquo;</span><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;"><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;" lang="en-US">GoodDeal</span></span><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">рекомендует&raquo; в профиле у исполнителя. Данный значок показывает, что этот исполнитель имеет на нашей платформе хорошую репутацию, выполнил большое количество заказов, является проверенным и люди ему доверяют.</span></p>' +
    '<p><span style="color: #444444; font-family: Times New Roman, serif;font-size: large;">2. Обратить внимание на отзывы и оценки. У каждого исполнителя в личном профиле есть средняя оценка и отзывы, которые доступны для просмотра всем пользователям нашего сервиса. После выполнения задания заказчики ставят исполнителю оценку и по желанию могут оставить отзыв. Хороший и ответственный исполнитель будет иметь хорошие оценки и отзывы.</span></p>' +
    '<p><span style="color: #444444; font-family: Times New Roman, serif;font-size: large;">3. Наличие значка &laquo;Я работаю открыто&raquo; в профиле у исполнителя. Каждый исполнитель может по собственному желанию заполнить свои паспортные данные, таким образом показывая, что он действует открыто.</span></p>' +
    '<p><span style="color: #444444; font-family: Times New Roman, serif;font-size: large;">4. Обратить внимание на количество выполненных заданий. Чем больше заданий исполнитель выполнил, тем больше вероятность того, что он имеет большой опыт.</span></p>' +
    '<p><span style="color: #444444; font-family: Times New Roman, serif;font-size: large;">5. Воспользоваться функцией &laquo;Безопасный платёж&raquo; для оплаты исполнителю. Данная функция позволит сервису зарезервировать средства между Вами (заказчиком) и исполнителем, и в случае, если исполнитель выполнит свою работу недобросовестно, недоделает её или попытается Вас обмануть, вернуть деньги не составит труда.</span></p>' +
    '<p><span style="color: #444444; font-family: Times New Roman, serif;font-size: large;">6. Обращайте внимание на организации. Наш сервис предоставляет возможность быть исполнителем как физическому лицу, так и организации (ИП/Юр. лицу).</span></p>' +
    '<p><span style="color: #444444; font-family: Times New Roman, serif;font-size: large;">7. Обращайте внимание на партнёров </span><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;"><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;" lang="en-US">GoodDeal</span></span><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">. Все организации-партнёры </span><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;"><span lang="en-US">GoodDeal</span></span><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;"> отображаются в соответствующем разделе на сайте, а так же помечаются специальными значками. Всего существует 3 категории партнёров: &laquo;Партнёр-Исполнитель&raquo;, &laquo;Партнёр-Магазин&raquo;, &laquo;Партнёр </span><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;"><span lang="en-US">GD</span></span><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">&raquo; (в данную категорию попали все партнёры, которые не вошли в предыдущие 2 категории).</span></p>' +
    '<p><span style="color: #444444; font-family: Times New Roman, serif;font-size: large;">Мы хотим обратить Ваше внимание, что мы стараемся поощрять наших добросовестных исполнителей, и прекращаем сотрудничество (блокируем) с недобросовестными. В связи с этим шанс встретить недобросовестного исполнителя минимален, а следуя нашим рекомендациям по выбору исполнителя, равен 0.</span></p>' +
    '<p><span style="color: #444444; font-family: Times New Roman, serif;font-size: large;">Так же при возникновении каких-либо споров и непонятных ситуаций, Вы можете воспользоваться функцией &laquo;Арбитраж&raquo;, написать в техподдержку или позвонить нам на горячую линию. Мы сделаем всё возможное для того, чтобы помочь Вам разрешить спорную ситуацию. </span></p>',

    howToChooseBonaFideCustomer:
    '<p><span style="color: #444444; font-family: Times New Roman, serif;font-size: large;">Работая с заказчиками и клиентами, у исполнителя всегда есть риск встретить недобросовестного, который не оплачивает услуги. В связи с этим, вполне логичен вопрос: &laquo;Как выбрать добросовестного заказчика и не быть обманутым?&raquo;. Ниже мы дадим Вам ответ на этот вопрос.</span></p>' +
    '<p><span style="color: #444444; font-family: Times New Roman, serif;font-size: large;">Прежде всего, мы хотим обратить ваше внимание на то, что с недобросовестными и избегающими оплаты заказчиками, мы прекращаем наше сотрудничество (блокируем). В связи с этим, шанс нарваться на недобросовестного клиента минимален.</span></p>' +
    '<p><span style="color: #444444; font-family: Times New Roman, serif;font-size: large;">И тем не менее, осторожность никогда не помешает, и чтобы найти добросовестного исполнителя, мы рекомендуем Вам придерживаться следующих правил:</span></p>' +
    '<p><span style="color: #444444; font-family: Times New Roman, serif;font-size: large;">1. Наличие значка &laquo;</span><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;"><span lang="en-US">GoodDeal</span></span><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;"> рекомендует&raquo; в профиле у клиента. Данный значок показывает, что этот клиент совершил большое количество заказов и не был замечен как &laquo;Недобросовестный&raquo;.</span></p>' +
    '<p><span style="color: #444444; font-family: Times New Roman, serif;font-size: large;">2. Искать задание с включенной функцией &laquo;Безопасный платёж&raquo;. Данная функция позволит сервису зарезервировать средства между заказчиком и Вами (исполнителем), и в этом случае услуга будет гарантированно оплачена.</span></p>' +
    '<p><span style="color: #444444; font-family: Times New Roman, serif;font-size: large;">Так же при возникновении каких-либо споров и непонятных ситуаций, Вы можете воспользоваться функцией &laquo;Арбитраж&raquo;, написать в техподдержку или позвонить нам на горячую линию. Мы сделаем всё возможное для того, чтобы помочь Вам разрешить спорную ситуацию. </span></p>',

    organizationRegistration:
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;" >Если Вы являетесь владельцем/представителем организации, мы рекомендуем зарегистрироваться в приложении как организация. Это даст Вам ряд преимуществ:</span></p>' +
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">- На Вас распространяются все пункты мотивационной программы точно так же, как и на физических лиц;</span></p>' +
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">- Многие заказчики доверительнее относятся к организациям;</span></p>' +
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">- Вам автоматически будет присвоен значок &laquo;Я действую открыто&raquo;. Во время регистрации организации Вы указываете данные о Вашей организации, в т.ч. ОГРН и ИНН. При условии, что все данные указаны корректно и верно, Ваша организация получает значок &laquo;Я действую открыто&raquo; сразу после регистрации;</span></p>' +
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">- При желании Вы можете стать партнёром </span><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;"><span lang="en-US">GoodDeal</span></span><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">. Если Вы зарегистрировали аккаунт организации в приложении, то сможете использовать все преимущества от этого статуса в приложении. </span></p>' +
    '<p><span style="color: #444444;"><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">Обратите внимание, что организации-заказчики/организации-исполнители могут работать только с обычным платежом.</span></span></p>',

    howToBecomeGoodDealPartner:
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">Будучи организацией, Вы можете стать партнёром </span><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;"><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;" lang="en-US">GoodDeal</span></span><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">. При этом если Вы уже зарегистрировали или будете регистрировать свою организацию в приложении </span><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;"><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;" lang="en-US">GoodDeal</span></span><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">, Вы сможете получить весь перечень преимуществ от этого статуса:</span></p>' +
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">- Значок партнёра в личном профиле, соответствующий категории партнёра (Партнёр-исполнитель, Партнёр-магазин, Партнёр GD (даётся всем партнёрам, не попадающим в две предыдущие группы));</span></p>' +
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">- Отображение организации в разделе &laquo;Партнёры&raquo;;</span></p>' +
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">- Размещение Вашего баннера сроком на одну неделю (7 дней) бесплатно;</span></p>' +
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">- Размещение 1 новости на сайте и в сообществе ВК бесплатно раз в месяц;</span></p>' +
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">- Скидки на услуги продвижения и рекламы: продвижение профилей и баннеры на сайте (все условия индивидуальны);</span></p>' +
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">- Приоритет в рассмотрении проблем и арбитражей (при наличии таковых)</span></p>' +
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">Если Вы хотите стать партнёром </span><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;"><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;" lang="en-US">GoodDeal</span></span><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">, Вам достаточно написать нам письмо на электронную почту </span><a style ="font-family: Times New Roman, serif; font-size: large;" href="mailto:office@gooddealonline.ru"><span style="color: #0000ff;"><u><span style="font-family: Times New Roman, serif; font-size: large;">office@gooddealonline.r</span></u></span><span style="color: #0000ff;"><u><span style="font-family: Times New Roman, serif; font-size: large;"><span lang="en-US">u</span></span></u></span></a><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;"> . В этом письме укажите название организации, Ваши контактные данные, а так же расскажите подробнее о своей компании; чем мы можем быть Вам полезны, и чем Вы можете быть полезны нам.</span></p>',

    howTheOrderPriceIsFormed:
    '<a name="order price"></a>' +
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">Формирование цены заказа интересует многих пользователей нашего приложения. В первую очередь нам стоит упомянуть, что все категории делятся на 2 вида: категории с &laquo;гибким тарифом&raquo; и обычные категории.</span></p>' +
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;"><strong>Как формируется цена заказа в категориях с &laquo;гибким тарифом&raquo;?</strong></span></p>' +
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">К категориям с &laquo;гибким тарифом&raquo; относятся категории: &laquo;Курьерские доставки&raquo; и &laquo;Грузоперевозки&raquo;. Цена на данные категории услуг формируется через гибкую систему тарифов, т.е. цена будет одинаковой у всех исполнителей и рассчитываться она будет исходя из главных критериев заказа, внешних факторов и дополнительных услуг к заказу.<br /> <br /> Хотим отметить, что в категории &laquo;Грузоперевозки &laquo;Грузовое такси&raquo; услуги погрузки/разгрузки не входят в итоговую стоимость заказа. Оплата за грузчиков производится отдельно.</span></p>' +
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;"><strong>Как формируется цена заказа в обычных категориях?</strong></span></p>' +
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">К данной группе относятся все остальные категории услуг. Цена на данные категории услуг формируется самими пользователями &ndash; при формировании предложения своих услуг исполнителями, или при формировании задания клиентами. В этом случае наши пользователи в праве сами выбрать наиболее подходящее для них предложение. </span></p>' +
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">На данный момент в обычных категориях доступна функция торга. Если исполнителя не устраивает сумма, которую заказчик готов заплатить за выполнение задания, исполнитель может воспользоваться функцией &laquo;Торг&raquo;. Таким образом он может указать сумму, за которую готов выполнить это задание. Если заказчика всё устроит, он выберет исполнителя. Если нет, он может предложить свою стоимость или просто проигнорировать заявку. Обратите внимание, что торг не ограничивает Вас в количестве предложений. Вы можете пользоваться этой функцией до тех пор, пока не придёте к согласию.</span></p>' +
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">Подробнее Вы можете ознакомиться с этим вопросом в документе </span><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;"><u><a style="color: #0000ff;" href="/support/pricing"><span style="font-family: Times New Roman, serif; font-size: large;">&laquo;Условия ценообразования&raquo;</span></a></u>, перейдя по ссылке</span></p>',

    InterestedTaskButNotSatisfiedWithTheAmount:
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">Здесь всё зависит от того, в какой категории создано задание. </span></p>' +
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">Если задание создано в категории с </span><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;"><strong>гибким тарифом</strong></span><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;"> (&laquo;Грузоперевозки. Расчёт по расстоянию&raquo;, &laquo;Грузоперевозки. Расчёт по часам&raquo; и &laquo;Курьерские доставки&raquo;), то с ценой Вы сделать ничего не сможете, так как в категориях с гибким тарифом стоимость рассчитывается автоматически искусственным интеллектом.</span></p>' +
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">Если задание создано в обычной категории (все категории, кроме:</span><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;"> &laquo;Грузоперевозки. Расчёт по расстоянию&raquo;, &laquo;Грузоперевозки. Расчёт по часам&raquo; и &laquo;Курьерские доставки&raquo;), то у исполнителя есть возможность предложить заказчику свою стоимость. Там он указывает сумму, за которую он готов выполнить задание. Если заказчика всё устроит, он выберет исполнителя. Если нет, он может предложить свою стоимость или просто проигнорировать заявку. Обратите внимание, что торг не ограничивает Вас в количестве предложений. Вы можете пользоваться этой функцией до тех пор, пока не придёте к согласию.</span></p>',

    whenWillTheFundsForMyWorkBeTransferred:
    '<a name="transfer_funds"></a>' +
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">Это зависит в первую очередь от того, какой способ оплаты был выбран.</span></p>' +
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">В случае, если Вы использовали безопасный платёж, сразу по окончанию Вашей работы Вам на виртуальный счёт </span><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;"><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;" lang="en-US">GoodDeal</span></span><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;"> будет зачислена сумма за вычетом комиссии. В дальнейшем эти деньги Вы сможете вывести с личного счёта. При выводе средств с личного счёта взимается комиссия в размере 60 рублей (Комиссия взимается сервисом, осуществляющим выплаты. Комиссия 60 рублей взимается за один вывод, по этому мы рекомендуем выводить средства за несколько выполненных заказов. Так Вы сможете больше сэкономить).</span></p>' +
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">Выведенные средства должны сразу поступать на банковский счёт/банковскую карту. В случае, если деньги в ближайшее время Вам не поступили, мы рекомендуем Вам подождать 24 часа, после этого обратиться в техподдержку </span><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;"><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;" lang="en-US">GoodDeal</span></span><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">.</span></p>' +
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">Если Вы использовали обычный платёж, то сроки оплаты Вашей работы Вы оговариваете с заказчиком.</span></p>',

    howToPayForTheService:
    '<a name="pay-service"></a>' +
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">В конце раздела &laquo;Создать задание&raquo; заказчик выбирает, каким способом оплатить необходимую услугу. Существует два способа оплаты: &laquo;Безопасный платеж&raquo; и обычный платеж.</span></p>' +
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">&laquo;Безопасный платеж&raquo; &ndash; вид платежа, в котором заказчик и исполнитель могут безопасно сотрудничать с </span><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;"><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;" lang="en-US">GoodDeal</span></span><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">. Заказчик указывает свои банковские реквизиты, и когда исполнитель для выполнения заказа найден, на его </span><span style="color: #444444;"><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">банковской карте резервируется необходимая для оплаты услуги сумма. Средства списываются и после успешного завершения задания&nbsp;переводятся на&nbsp;виртуальный счет исполнителя. </span></span><span></span><span style="color: #444444;"><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">Если задание не выполнено, деньги возвращаются обратно заказчику. Этот способ обеспечивает максимальную безопасность и гарантированный возврат ваших денежных средств заказчику, а исполнителю получение денежного вознаграждения в случае, если задание было выполнено качественно.</span></span></p>' +
    '<p><span style="color: #444444;"><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">Обычный платеж подразумевает самостоятельную оплату задания заказчиком. Он может оплатить услугу исполнителю двумя видами: &laquo;Наличными&raquo; и &laquo;С карты на карту&raquo;. В момент завершения задания заказчик оплачивает услугу исполнителю самостоятельно. В этом случае </span></span><span><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;"><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;" lang="en-US">GoodDeal</span></span></span><span><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;"> не сможет никак повлиять на транзакцию и участники сделки несут персональную ответственность. Чтобы было меньше вопросов и разногласий, при обычном платеже мы рекомендуем заключить договор. </span></span></p>' +
    '<p><span style="color: #444444;"><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">Обратите внимание, что если Вы являетесь организацией, или хотите, чтобы организация могла взяться за Ваше задание, Вам необходимо выбрать обычный платёж. Организации могут работать только с обычными платежами.</span></span></p>',

    whatIsSafePayment:
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">Функция &laquo;Безопасный платёж&raquo; введена для того, чтобы обезопасить Вас от недобросовестных пользователей. При совершении сделки в режиме &laquo;Безопасный платёж&raquo; на карте клиента будут зарезервированы средства для оплаты услуги до тех пор, пока исполнитель не выполнит задание.</span></p>' +
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">Данная функция полезна как для исполнителей, так и для заказчиков:</span></p>' +
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">- Если исполнитель оказал услугу не качественно или недоделал её, заказчик без труда сможет вернуть себе средства.</span></p>' +
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">- Если исполнитель сделал всё </span><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;"><u>добросовестно</u></span><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">, но клиент решил не принимать услугу &ndash; исполнитель всё равно получит средства, которые были зарезервированы системой для оплаты услуги</span></p>' +
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">Обратите Ваше внимание, что при возникновении разногласий если стороны не могут самостоятельно разрешить свой спор, они смогут воспользоваться функцией &laquo;Арбитраж&raquo;. В этом случае к чату подключится администратор </span><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;"><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;" lang="en-US">GoodDeal</span></span><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;"> и постарается разрешить все споры и разногласия.</span></p>' +
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">Данный вид платежа не доступен для организаций.</span></p>',

    howToWithdrawFunds:
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">Вывести средства со своего аккаунта можно в разделе &laquo;мой профиль&raquo;. В данном разделе будет находиться кнопка &laquo;вывести&raquo;. Нажимаете на нее, и </span><span style="color: #444444;"><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">в течение дня </span></span><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">средства будут перечислены вам на банковскую карту.</span></p>' +
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">При этом необходимо отметить, что Стоимость вывода средств составляет 60 рублей за один вывод (Данная комиссия взимается сервисом, осуществляющим выплаты). Не важно, какую сумму вы собираетесь выводить, стоимость вывода всегда остаётся 60 рублей. По этой причине мы рекомендуем выводить средства сразу за несколько выполненных заданий. Таким образом Вы сможете сэкономить на уплате комиссии. Обращаем Ваше внимание, что вывод средств может занять некоторое время (До 24 часов). В случае, если прошло уже более 24 часов, Вам необходимо обратиться в техподдержку </span><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;"><span lang="en-US">GoodDeal</span></span><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">.</span></p>',

    whatShouldIDoAfterFormingTask:
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">После того, как Вы сформировали задание, его необходимо опубликовать. Для этого Вам необходимо нажать кнопку &laquo;Создать задание&raquo; и ждать пока на него откликнутся исполнители.</span></p>',

    whenWillIReceiveOffers:
    '<a name="get-offers"></a>' +
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">Для Исполнителей: </span></p>' +
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">- Вы получите предложение в случае, когда Клиент создаст задание и выберет вас в качестве исполнителя. </span></p>' +
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">- Также вы можете сами выбрать себе задание. Переходите в раздел &laquo;Найти задание&raquo; и выбираете подходящую для вас задачу. Для более удобного поиска задачи можно воспользоваться различными фильтрами. Справа в верхнем углу находится фильтр поиска задач. Кликая на него, вы сможете ускорить поиск необходимого задания в зависимости от различных условий заказа (Стоимость задания, категория/подкатегория задания, место оказания услуги, регион/город, дата создания, тип платежа и т.д.).</span></p>' +
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">Когда вы нашли интересующее вас задание, вы кликаете на него и нажимаете кнопку &laquo;предложить свои услуги&raquo;. Далее Клиент рассматривает вашу кандидатуру, и если она его устраивает, он нажимает &laquo;назначить исполнителем&raquo; и ,тем самым, подтверждает , что вы можете приступать к выполнению задания. После этого вам приходит уведомление о том, что Заказчик выбрал вас в качестве Исполнителя, и вам необходимо снова зайти на страничку задания и нажать на кнопку &laquo;Приступить к выполнению&raquo;, чтобы официально начать выполнять ее. Тем самым, вы подтверждаете статус, что вы действительно Исполнитель данной задачи и согласны ее выполнить.</span></p>' +
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">Для заказчиков: </span></p>' +
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">Вы получите предложения после того как:<br /> - Сформируете заказ в разделе &laquo;Создать задание&raquo;. Затем после опубликования задания исполнители могут предложить свои услуги в зависимости от категории задания, вы их рассматриваете и выбираете того исполнителя, который вам больше понравился.</span></p>' +
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">- Также после опубликования задачи вы можете сами предложить исполнителям выполнить задание. Для этого, после создания задачи вам приходит надпись &laquo;Предложить задачу. Желаете ли Вы предложить задачу исполнителю?&raquo; с двумя кнопками. &laquo;Отменить&raquo; (Кликая на нее, вы отказываетесь предлагать задачу исполнителю в настоящий момент. При этом вовсе не значит, что вы больше не сможете предложить задачу исполнителю. Вы сможете в любой момент предложить ее, перейдя в раздел &laquo;Исполнители&raquo;) и &laquo;Перейти к выбору исполнителя&raquo;.Кликая на вторую, вы автоматически переходите в раздел &laquo;Исполнители&raquo;, где сможете выбрать подходящего вам специалиста. Для более эффективного поиска, можете воспользоваться фильтром (Справа в верхнем углу). При клике на него, вы сможете ускорить поиск специалиста исходя определенных критериев (рейтинг, количество завершенных задач, регион/город, категория/подкатегория).</span></p>',

    howContractorLinkExamplesOfHisWork:
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">Данная возможность есть у пользователя в личном профиле. Спускайтесь до раздела &laquo;Примеры работ&raquo;, кликаете на серый карандашик и можете выкладывать фото/видео своих работ в личный профиль.</span></p>',

    canPerformerReceiveNotificationsAboutTasksCreatedHisCity:
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">Да. Такая возможность есть. Заходите в личный профиль и спускаетесь до переключателя &laquo;Получать уведомления только о заданиях, созданных в моем городе&raquo;. Активируйте его простым нажатием и получайте уведомления о созданных заданиях только в вашем городе.</span></p>',

    whatToDoOfDifficultiesQuestionsAndDisputes:
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">При возникновении каких-либо трудностей, вопросов, недопониманий, споров и разногласий, Вы можете обратиться в техподдержку, написав в соответствующем разделе на сайте или в приложении, а так же Вы можете позвонить нам в </span><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;"><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;" lang="en-US">Call</span></span><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">-центр.</span></p>' +
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">В случае, если у Вас возникли споры или разногласиями со второй стороной, Вы можете обратиться в службу &laquo;Арбитраж&raquo;, где администрация </span><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;"><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;" lang="en-US">GoodDeal</span></span><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;"> готова решить ваши разногласия и споры максимально оперативно.</span></p>',

    whySpecifyPassportData:
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">Указание паспортных данных является необязательным полем, однако желательным (особенно для исполнителей). Указывая свои паспортные данные Вы показываете нам, что действуете открыто, собираетесь выполнять все задания добросовестно и не собираетесь обманывать заказчиков. </span></p>' +
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">Паспортные данные будут доступны только администрации и разработчикам приложения, т.е. другие пользователи не будут видеть Ваши паспортные данные.</span></p>' +
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">Мы ценим открытость, и за это мы прикрепляем к вашему профилю значок &laquo;Я действую открыто&raquo;, что привлечёт к Вам больше заказчиков и вероятность того, что именно Вас выберут в качестве исполнителя, возрастает, т.к. заказчик заинтересован в получении хорошего сервиса и услуг.</span></p>' +
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">Помимо этого, мы повысим Вашу среднюю оценку на 0,2 балла по 5-тибальной шкале, что так же может повлиять на выбор клиента в вашу сторону.</span></p>',

    iWasBlocked:
    '<p><span style="color: #444444;"><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">Причина Вашей блокировки должна быть указана в профиле аккаунта.</span></span><span style="color: #444444;"><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;"><br /> </span></span><span style="color: #444444;"><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">Для того, чтобы снять блокировку Вам необходимо выждать, пока период блокировки пройдёт. Вы так же можете снять блокировку, заплатив штраф.</span></span><span style="color: #444444;"><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;"><br /> </span></span><span style="color: #444444;"><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">Оставшееся время блокировки и сумма штрафа указана там же, где и причина блокировки.</span></span></p>' +
    '<p><span style="color: #444444;"><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;"></span></span><span style="color: #444444;"><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">Для того, чтобы Вас не блокировали, просим Вас придерживаться правил GoodDeal и относиться ответственно к заказам и заданиям. Так же мы рекомендуем ознакомиться повторно с системой жалоб и наказаний на сайте в разделе &laquo;О компании&raquo;, подразделе &laquo;Документация&raquo;.</span></span></p>',

    whatArePromotionsAndIncentives:
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">При использовании нашего приложения исполнители могут получить дополнительные поощрения от </span><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;"><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;" lang="en-US">GoodDeal</span></span><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">, если будут относиться к заказам ответственно. Исполнителям будут даваться бонусы </span><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;"><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;" lang="en-US">GD</span></span><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;"> для того, чтобы они могли брать больше заказов без комиссии.</span></p>' +
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">Исполнителям для получения большинства акций достаточно просто добросовестно подходить к заказам &ndash; не отменять их, если они уже взялись, то выполнять работу качественно. </span></p>' +
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">Для организаций </span><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;"><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;" lang="en-US">GoodDeal</span></span><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;"> предусмотрел ещё ряд дополнительных акций, о которых можете узнать в мотивационной программе.</span></p>' +
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">Более того, в приложении есть раздел &laquo;Акции&raquo;. В этом разделе Вы сможете найти все действующие на данный момент в GoodDeal акции, спецпредложения, и бонусные программы.</span></p>' +
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">Более подробную информацию Вы можете просмотреть, перейдя по ссылке на документ </span><span style="color: #0000ff;"><u><a href="/support/motivation_programm"><span style="color: #0000ff; font-family: Times New Roman, serif; font-size: large;">&laquo;Мотивационная программа&raquo;</span></a></u></span><span style="color: #0000cc;"><span style="font-family: Times New Roman, serif; font-size: large;"><u>.</u></span></span><span style="color: #444444;"><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;"> Этот документ Вы можете найти на нашем сайте в разделе &laquo;О компании&raquo;</span></span><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">.</span></p>',

    didNotReceiveMoneyForTheCompletedTask:
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;"><em><strong>Вы пользовались обычным платежом, или безопасным?</strong></em></span></p>' +
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">Если Вы пользовались обычным платежом, Вам необходимо воспользоваться функцией &laquo;Арбитраж&raquo;, которая находится в нижней части сайта. В приложении находится в разделе &laquo;настройки&raquo;. Чтобы попасть в настройки, Вам необходимо открыть свой профиль и нажать на значок шестерёнки в правом верхнем углу. После того, как чат арбитража откроется, Вам необходимо будет максимально детально описать свою проблему. В ближайшее время Администратор ответит Вам и постарается максимально быстро решить проблему.</span></p>' +
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;"><em><strong>Если Вы пользовались безопасным платежом, нажали ли Вы &laquo;Заказ завершён&raquo; в приложении?</strong></em></span></p>' +
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">Если Вы не нажали &laquo;Заказ завершён&raquo;, то Вам необходимо в приложении нажать на кнопку &laquo;Заказ завершён&raquo;. Если Вы оказывали услугу в категориях&laquo;с гибким тарифом&raquo;( Курьерские доставки и Грузоперевозки &laquo;Грузовое такси&raquo;), то деньги должны прийти в течение 2-х часов, а если в обычных категориях (все остальные), то деньги должны прийти в течение 26 часов.</span></p>' +
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;"><em><strong>Если Вы нажали &laquo;Заказ завершён&raquo;, открылась ли функция арбитража?</strong></em></span></p>' +
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">Если функция арбитража открылась, значит у клиента возникли какие-либо вопросы или недовольства, и Вам, совместно с администратором, необходимо решить возникшую проблему в чате арбитража.</span></p>' +
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;"><em><strong>Если функция арбитража не открылась, в какой категории Вы оказывали услуги и сколько прошло с момента нажатия им кнопки &laquo;заказ завершён&raquo;?</strong></em></span></p>' +
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">Если Вы оказывали услуги в категориях&laquo;с гибким тарифом&raquo;(Курьерские доставки и Грузоперевозки) и прошло более 2-х часов с момента завершения Вами заказа, значит возможны какие-либо технические неполадки с сервером, и мы рекомендуем подождать 24 часа. За этот период деньги точно должны будут поступить Вам. В случае, если через 24 часа деньги не поступят на счёт, необходимо обратиться в чат техподдержки указав, сколько прошло с момента выполнения заказа, какой вид платежа вы использовали, в какой категории оказывали услугу. Администратор постарается решить Вашу проблему в кратчайшие сроки.</span></p>' +
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">Если Вы оказывали услуги в категориях&laquo;с гибким тарифом&raquo; (Курьерские доставки и Грузоперевозки) и прошло менее 2-х часов с момента завершения им заказа, то ему следует подождать ещё некоторое время, пока деньги переведутся на его счёт.</span></p>' +
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">Если Вы оказывали услуги в обычных категориях (все, кроме Курьерские доставки и Грузоперевозки ) и прошло более 24 часов с момента завершения Вами заказа, значит возможны какие-либо технические неполадки с сервером, и мы рекомендуем подождать ещё 24 часа. За этот период деньги точно должны будут дойти до Вас. В случае, если через 24 часа деньги не поступят на счёт, необходимо обратиться в чат техподдержки указав, сколько прошло с момента выполнения заказа, какой вид платежа вы использовали, в какой категории оказывали услугу. Администратор постарается решить Вашу проблему в кратчайшие сроки.</span></p>' +
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">Если Вы оказывали услуги в обычных категориях (все, кроме Курьерские доставки и Грузоперевозки) и прошло менее 26 часов с момента завершения им заказа, то Вам следует подождать ещё некоторое время, пока деньги переведутся на его счёт.</span></p>',

    theyDoNotChoosePerformerAndDoNotGiveAssignments:
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">Если Вам не дают заданий, то причины могут быть 2:</span></p>' +
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">1. Возможно, у Вас плохая репутация. Если у Вас низкий рейтинг в нашем приложении, плохие отзывы, то заказчики могут не давать Вам задания, т.к. они опасаются недобросовестного подхода к выполнению задания. Свой рейтинг и отзывы Вы можете просмотреть в личном профиле.</span></p>' +
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">Что в таких ситуациях можно сделать? Во-первых, не отказываться от заданий, которые Вам уже поручили, или за которые Вы уже взялись. Во-вторых, выполняйте задания ответственно и качественно, чтобы Вам начали ставить хорошие оценки и оставлять хорошие отзывы. В-третьих, рекомендуем указать свои паспортные данные в личном профиле. Указывая свои паспортные данные Вы показываете нам, что действуете открыто, собираетесь выполнять все задания добросовестно и не собираетесь обманывать заказчиков. Мы ценим открытость, и за это мы прикрепляем к вашему профилю значок &laquo;Я действую открыто&raquo;, что привлечёт к Вам больше заказчиков и вероятность того, что именно Вас выберут в качестве исполнителя, возрастает, т.к. заказчик заинтересован в получении хорошего сервиса и услуг.Помимо этого, мы повысим Вашу среднюю оценку на 0,2 балла по 5-тибальной шкале, что так же может повлиять на выбор клиента в вашу сторону.</span><span style="color: #444444;"><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;"> Этот документ Вы можете найти на нашем сайте в разделе &laquo;О компании&raquo;</span></span><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">).</span></p>' +
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">2. Возможно, Ваши потенциальные заказчики на данный момент ещё не пользуются нашим приложением в данной категории/подкатегории. Мы просим подойти к этому с пониманием, т.к. наше приложение находится ещё на ранней стадии развития. Мы прикладываем все возможные усилия для того, чтобы в ближайшее время больше потенциальных заказчиков, которые могут дать Вам задание, начали пользоваться приложением. </span><br /> </p>',

    lowRating:
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">Во-первых, не отказываться от заданий, которые Вам уже поручили, или за которые Вы уже взялись. </span></p>' +
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">Во-вторых, выполняйте задания ответственно и качественно, чтобы Вам начали ставить хорошие оценки и оставлять хорошие отзывы. </span></p>' +
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">В-третьих, рекомендуем указать свои паспортные данные в личном профиле. Указывая свои паспортные данные, Вы показываете нам что действуете открыто, собираетесь выполнять все задания добросовестно и не собираетесь обманывать заказчиков .Мы ценим открытость, и за это мы прикрепляем к вашему профилю значок &laquo;Я действую открыто&raquo;, что привлечёт к Вам больше заказчиков и вероятность того, что именно Вас выберут в качестве исполнителя, возрастает, т.к. заказчик заинтересован в получении хорошего сервиса и услуг. Помимо этого, мы повысим Вашу среднюю оценку на 0,2 балла по 5-тибальной шкале, что так же может повлиять на выбор клиента в вашу сторону. </span></p>',

    whatAreOrderFulfillmentModes:
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">В категориях с &laquo;гибким тарифом&raquo; (Курьерские доставки и Грузоперевозки) существуют 3 режима выполнения заказов:</span></p>' +
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">Обычный&ndash;исполнитель начинает работу по факту отклика на Ваше задание и утверждение Вами его кандидатуры</span></p>' +
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">На дату и время &ndash; выполнение заказа исполнителем в указанные заказчиком сроки.</span></p>' +
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">Срочно &ndash; быстрый поиск исполнителя и выполнение им заказа в кротчайшие сроки (Задача будет показываться выше в поиске, а стоимость задания увеличится на 20%)</span></p>' +
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">В обычных категориях (Все, кроме: Курьерские доставки и Грузоперевозки) существует только два режима выполнения):</span></p>' +
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">Обычный&ndash;исполнитель начинает работу по факту отклика на Ваше задание и утверждение Вами его кандидатуры. </span></p>' +
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">На дату и время &ndash; выполнение заказа исполнителем в указанные заказчиком сроки</span></p>',

    whatAreGDbonuses:
    '<p><a name="_GoBack"></a> <span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">Этот счет используется для оплаты комиссии исполнителя, когда он выполненяет задания с обычным платежом.<br /> </span></p>' +
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">В процессе взятия задания с обычным платежом, у исполнителя выйдет окошко с суммой. Эта сумма и будет являться комиссией. Для взятия задания исполнителю необходимо оплатить эту комиссию. Для уплаты комиссии необходимо будет нажать соответствующую кнопку и следовать дальнейшим инструкциям.<br /> </span></p>' +
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">Так же на этот счёт будут приходить различные бонусы, если вы являетесь исполнителем и свои заказы выполняете качественно и добросовестно. Более подробную информацию Вы можете просмотреть, перейдя по ссылке на документ </span><span style="color: #0000ff;"><u><a href="/support/motivation_programm"><span style="color: #0000ff; font-family: Times New Roman, serif; font-size: large;">&laquo;Мотивационная программа&raquo;</span></a></u></span><span style="color: #0000cc;"><span style="font-family: Times New Roman, serif; font-size: large;"><u>.</u></span></span><span style="color: #444444;"><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;"> Этот документ Вы можете найти на нашем сайте в разделе &laquo;О компании&raquo;</span></span><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">.</span></p>',

    howLongToWaitForRefund:
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">В случае если исполнитель недобросовестно подошёл к заданию и в арбитраже Администратор был на Вашей стороне, Вам вернутся деньги, которые были потрачены на задание.</span></p>' +
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">Специфика системы такова, что возврат средств &ndash; самая долгая операция в </span><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;"><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;" lang="en-US">GoodDeal</span></span><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">. Деньги могут возвращаться до 4 суток (96 часов) с момента завершения арбитража. Мы просим набраться Вас терпения. В случае, если по истечению 4 суток деньги не вернулись, Вам следует обратиться в техподдержку, максимально детально описав возникшую проблему, а так же указать дату и время разрешения арбитража.</span></p>' +
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">Напоминаем, что деньги Вам сможет вернуть </span><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;"><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;" lang="en-US">GoodDeal</span></span><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;"> только в случае, если Вы выбирали безопасный платёж.</span></p>',

    howToOrderPlacementOfAnAdvertisingBanner:
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">Если Вы хотите разместить рекламный баннер на сайте </span><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;"><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;" lang="en-US">GoodDeal</span></span><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">, то вам необходимо написать нам сообщение на электронную почту </span><a href="mailto:office@gooddealonline.ru"><span style="color: #0000ff;"><u><span style="font-family: Times New Roman, serif; font-size: large;">office@gooddealonline.r</span></u></span><span style="color: #0000ff;"><u><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;"><span lang="en-US">u</span></span></u></span></a><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;"> . Там Вы должны будете указать название организации и что будете рекламировать, а так же есть ли у Вас уже готовый баннер (размеры рекламного баннера: 300x500). Мы Вам ответим в ближайшее время и предложим наиболее удобные для Вас позиции.</span></p>' +
    '<p><span style="color: #444444; font-family: Times New Roman, serif; font-size: large;">Обращаем Ваше внимание на то, что если Вы закажете размещение баннера сроком на месяц или меньше, разработка рекламного баннера будет платной.</span></p>',

    whatIsGoodDealJob:
    '<a name="what-is-GoodDeal-job"></a>' +
    '<p style="color: #444444;margin-top:0pt; margin-bottom:10pt; line-height:115%; font-size:14pt"><span style="font-family:Times New Roman">GoodDeal.работа – это одно из направлений деятельности приложения GoodDeal. GoodDeal.работа позволяет работодателям найти новых сотрудников, а людям в поиске работы найти подходящую работу.</span></p><p style="color: #444444;margin-top:0pt; margin-bottom:10pt; line-height:115%; font-size:14pt"><span style="font-family:Times New Roman">GoodDeal.работа охватывает все сферы жизнедеятельности, таким образом создаёт удобный сервис по поиску работы и новых сотрудников</span></p>',

    howSearchJob:
    '<a name="how-search-job"></a>' +
    '<p style="color: #444444;margin-top:0pt; margin-bottom:10pt; line-height:115%; font-size:14pt"><span style="font-family:Times New Roman">Чтобы найти работу, мы рекомендуем в первую очередь максимально детально заполнить своё резюме. Создать/редактировать резюме Вы можете, кликнув на кнопку «Создать резюме» в главном меню приложения, а так же кликнув на кнопку «Моё резюме» через личный профиль.</span></p><p style="color: #444444;margin-top:0pt; margin-bottom:10pt; line-height:115%; font-size:14pt"><span style="font-family:Times New Roman">После того, как Вы заполните всю информацию о себе, Вы можете ожидать откликов со стороны работодателя, или же обратить внимание работодателя на свою кандидатуру, направив своё резюме в ответ на размещённую работодателем вакансию.</span></p>',

    howSearchEmployeeJob:
    '<p style="color: #444444;margin-top:0pt; margin-bottom:10pt; line-height:115%; font-size:14pt"><span style="font-family:Times New Roman">Чтобы найти сотрудника, мы рекомендуем в первую очередь максимально детально заполнить вакансию. Создать вакансию Вы можете при помощи кнопки «Создать вакансию» в главном меню приложения.</span></p><p style="color: #444444;margin-top:12pt; margin-bottom:10pt; line-height:115%; font-size:14pt"><span style="font-family:Times New Roman">После того, как Вы заполните всю информацию об открытой вакансии, Вы можете ожидать откликов со стороны соискателей, или же начать поиск самостоятельно, просматривая резюме соискателей и направляя им информацию о своей вакансии. </span></p><p style="color: #444444;margin-top:12pt; margin-bottom:10pt; line-height:115%; font-size:14pt"><span style="font-family:Times New Roman">Редактировать информацию о вакансии Вы можете через личный профиль. Для этого Вам необходимо перейти в личный профиль, раздел «Моя работа». Далее выберите раздел «Мои вакансии», найдите нужную вакансию и из профиля вакансии начните редактирование.</span></p>',

    whereContactJob:
    '<a name="where-contact-job"></a>' +
    '<p style="color: #444444;margin-top:12pt; margin-bottom:10pt; line-height:115%; font-size:14pt"><span style="font-family:Times New Roman">Контакты работодателя отображаются в профиле вакансии, справа от информации по предлагаемой вакансии.</span></p><p style="color: #444444;margin-top:12pt; margin-bottom:10pt; line-height:115%; font-size:14pt"><span style="font-family:Times New Roman">Контакты соискателя можно посмотреть следующим образом:<br /> Необходимо предложить вакансию конкретному соискателю, в случае если соискателя заинтересует данная вакансия, он переадресует на нее свое резюме. После отклика соискателя, в профиле вакансии будет отображаться его карточка с отправленным резюме. Для просмотра резюме кликнете на кнопку &laquo;Просмотр резюме&raquo;. В самом низу резюме расположена кнопка &laquo;Показать контактные данные соискателя&raquo;. Нажав на эту кнопку, Вам откроется вся контактная информация о кандидате.</span></p>',
    createResumeJob:
    '<a name="create-resume-job"></a>' +
    '<p style="color: #444444;margin-top:12pt; margin-bottom:10pt; line-height:115%; font-size:14pt"><span style="font-family:Times New Roman">Изначально Вы можете создать одно резюме (как создать резюме – см. пункт 1). Данное резюме будет доступно для потенциальных работодателей, будет отображаться у Вас в профиле и в разделе «Найти работника» напротив Вашего профиля.</span></p><p style="color: #444444;margin-top:12pt; margin-bottom:10pt; line-height:115%; font-size:14pt"><span style="font-family:Times New Roman">Если Вы будете откликаться на созданные работодателем Вакансии, то во время отправки резюме Вам будет даваться возможность изменить своё резюме и подстроить его под конкретную вакансию. Направив изменённое резюме создателю вакансии, ему будет отображаться именно изменённое резюме.</span></p><p style="color: #444444;margin-top:12pt; margin-bottom:10pt; line-height:115%; font-size:14pt"><span style="font-family:Times New Roman">Обратите внимание, что изменяя резюме при отклике на вакансию, основное резюме в Вашем профиле изменяться не будет.</span></p>',

    haveComissionJob:
    '<a name="have-comission-job"></a>' +
    '<p style="color: #444444;margin-top:12pt; margin-bottom:10pt; line-height:115%; font-size:14pt"><span style="font-family:Times New Roman">На данный момент сервис GoodDeal.работа абсолютно бесплатный для всех пользователей. В нём отсутствуют какие – либо комиссии и платежи.</span></p>',

    howSearchPersonJob:
    '<a name="how-search-person-job"></a>' +
    '<p style="color: #444444;margin-top:12pt; margin-bottom:10pt; line-height:115%; font-size:14pt"><span style="font-family:Times New Roman">При поиске работника/работы обращайте внимание на профиль работодателя: насколько подробно он заполнен. Мы рекомендуем относиться с осторожностью к пустым профилям. Также тщательно смотрите условия работы, описанные в вакансии пользователя.</span></p><p style="color: #444444;margin-top:12pt; margin-bottom:10pt; line-height:115%; font-size:14pt"><span style="font-family:Times New Roman">При поиске работника обращайте внимание на профиль соискателя: насколько подробно он заполнен. Мы рекомендуем относиться с осторожностью к пустым профилям. Также тщательно смотрите на опыт работы, навыки и качества, описанные в резюме пользователя.</span></p><p style="color: #444444;margin-top:12pt; margin-bottom:10pt; line-height:115%; font-size:14pt"><span style="font-family:Times New Roman">Обратите внимание на наличие дополнительных статусов у профиля (Например, статус «GoodDeal рекомендует» или «Я действую открыто»).</span></p>',

    whoCreateVacancyJob:
    '<p style="color: #444444;margin-top:12pt; margin-bottom:10pt; line-height:115%; font-size:14pt"><span style="font-family:Times New Roman">Вакансии могут создаваться любыми пользователями: Как физическими, так и юридическими лицами.</span></p>',

    iHaveResumeVacncyWhatDoJob:
    '<p style="color: #444444;margin-top:12pt; margin-bottom:10pt; line-height:115%; font-size:14pt"><span style="font-family:Times New Roman">Вы можете начать самостоятельный поиск соискателей/работы, посещая разделы «Найти работу» / «Найти работника» и просматривая существующие предложения, либо ожидать, когда работодатель / соискатель сами откликнутся на Ваше резюме (подробнее см. пункты 2 «Как найти работу?» и 3 «Как найти сотрудника?»)</span></p>',

    whatDoIfNotVacancyJob:
    '<p style="color: #444444;margin-top:0pt; margin-bottom:10pt; line-height:115%; font-size:14pt"><span style="font-family:Times New Roman">В этом случае создайте своё резюме/вакансию и ожидайте, пока на них откликнутся потенциальные работодатели/сотрудники.</span></p>',

    registrationOrgJob:
    '<p style="color: #444444;margin-top:0pt; margin-bottom:0pt; line-height:115%; font-size:14pt"><span style="font-family:Times New Roman">Если Вы являетесь владельцем/представителем организации, мы рекомендуем зарегистрироваться в приложении как организация. Это даст Вам ряд преимуществ: - На Вас распространяются все пункты мотивационной программы точно так же, как и на физических лиц;</span></p><p style="color: #444444;margin-top:0pt; margin-bottom:0pt; line-height:115%; font-size:14pt"><span style="font-family:Times New Roman; -aw-import:spaces">&#xa0;</span><span style="font-family:Times New Roman">- Многие заказчики и соискатели доверительнее относятся к организациям;</span></p><p style="color: #444444;margin-top:0pt; margin-bottom:0pt; line-height:115%; font-size:14pt"><span style="font-family:Times New Roman; -aw-import:spaces">&#xa0;</span><span style="font-family:Times New Roman">- Вам автоматически будет присвоен значок «Я действую открыто». Во время регистрации организации Вы указываете данные о Вашей организации, в т.ч. ОГРН и ИНН. При условии, что все данные указаны корректно и верно, Ваша организация получает значок «Я действую открыто» сразу после регистрации;</span></p><p style="color: #444444;margin-top:0pt; margin-bottom:0pt; line-height:115%; font-size:14pt"><span style="font-family:Times New Roman; -aw-import:spaces">&#xa0;</span><span style="font-family:Times New Roman">- При желании Вы можете стать партнёром GoodDeal. Если Вы зарегистрировали аккаунт организации в приложении, то сможете использовать все преимущества от этого статуса в приложении. </span></p>',

    howStayPartnerJob:
    '<p style="color: #444444;margin-top:0pt; margin-bottom:0pt; line-height:115%; font-size:14pt"><span style="font-family:Times New Roman">Будучи организацией, Вы можете стать партнёром GoodDeal. При этом если Вы уже зарегистрировали или будете регистрировать свою организацию в приложении GoodDeal, Вы сможете получить весь перечень преимуществ от этого статуса:</span></p><p style="color: #444444;margin-top:0pt; margin-bottom:0pt; line-height:115%; font-size:14pt"><span style="font-family:Times New Roman; -aw-import:spaces">&#xa0;</span><span style="font-family:Times New Roman">- Значок партнёра в личном профиле, соответствующий категории партнёра (Партнёр-исполнитель, Партнёр-магазин, Партнёр GD (даётся всем партнёрам, не попадающим в две предыдущие группы));</span></p><p style="color: #444444;margin-top:0pt; margin-bottom:0pt; line-height:115%; font-size:14pt"><span style="font-family:Times New Roman">- Отображение организации в разделе «Партнёры»;</span></p><p style="color: #444444;margin-top:0pt; margin-bottom:0pt; line-height:115%; font-size:14pt"><span style="font-family:Times New Roman">- Размещение Вашего баннера сроком на одну неделю (7 дней) бесплатно;</span></p><p style="color: #444444;margin-top:0pt; margin-bottom:0pt; line-height:115%; font-size:14pt"><span style="font-family:Times New Roman">- Размещение 1 новости на сайте и в сообществе ВК бесплатно раз в месяц;</span></p><p style="color: #444444;margin-top:0pt; margin-bottom:0pt; line-height:115%; font-size:14pt"><span style="font-family:Times New Roman">- Скидки на услуги продвижения и рекламы: продвижение профилей и баннеры на сайте (все условия индивидуальны);</span></p><p style="color: #444444;margin-top:0pt; margin-bottom:10pt; line-height:115%; font-size:14pt"><span style="font-family:Times New Roman; -aw-import:spaces">&#xa0;</span></p><p style="color: #444444;margin-top:0pt; margin-bottom:0pt; line-height:115%; font-size:14pt"><span style="font-family:Times New Roman">Если Вы хотите стать партнёром GoodDeal, Вам достаточно написать нам письмо на электронную почту </span><a href="mailto:office@gooddealonline.ru" style="text-decoration:none"><span style="font-family:Times New Roman; text-decoration:underline; color:#0000ff">office@gooddealonline.ru</span></a><span style="font-family:Times New Roman"> . В этом письме укажите название организации, Ваши контактные данные, а так же расскажите подробнее о своей компании; чем мы можем быть Вам полезны, и чем Вы можете быть полезны нам.</span></p>',

    whatMeDoWithDifficultJob:
    '<p style="color: #444444;margin-top:0pt; margin-bottom:0pt; line-height:115%; font-size:14pt"><span style="font-family:Times New Roman; font-weight:bold; -aw-import:ignore">&#xa0;</span></p><p style="color: #444444;margin-top:0pt; margin-bottom:0pt; line-height:115%; font-size:14pt"><span style="font-family:Times New Roman">При возникновении каких-либо трудностей, вопросов и недопониманий, Вы можете обратиться в техподдержку, написав в соответствующем разделе на сайте или в приложении, а так же Вы можете позвонить нам в Call-центр.</span></p>',

    whyPasportJob:
    '<p style="color: #444444;margin-top:0pt; margin-bottom:10pt; line-height:115%; font-size:14pt"><span style="font-family:Times New Roman">Указание паспортных данных является необязательным полем, однако желательным. Указывая свои паспортные данные Вы показываете нам, что действуете открыто, собираетесь подходить ответственно и осознанно к своим действиям в приложении. </span></p><p style="color: #444444;margin-top:0pt; margin-bottom:10pt; line-height:115%; font-size:14pt"><span style="font-family:Times New Roman">Паспортные данные будут доступны только администрации и разработчикам приложения, т.е. другие пользователи не будут видеть Ваши паспортные данные.</span></p><p style="color: #444444;margin-top:0pt; margin-bottom:10pt; line-height:115%; font-size:14pt"><span style="font-family:Times New Roman">Мы ценим открытость, и за это мы прикрепляем к вашему профилю значок «Я действую открыто», что привлечёт к Вам больше заказчиков и вероятность того, что именно Вас выберут в качестве исполнителя, возрастает, т.к. заказчик заинтересован в получении хорошего сервиса и услуг.</span></p><p style="color: #444444;margin-top:0pt; margin-bottom:10pt; line-height:115%; font-size:14pt"><span style="font-family:Times New Roman">Помимо этого, мы повысим Вашу среднюю оценку на 0,2 балла по 5-тибальной шкале, что так же может повлиять на выбор клиента в вашу сторону.</span></p>',

    howPayReklamaJob:
    '<p style="color: #444444;margin-top:0pt; margin-bottom:0pt; line-height:115%; font-size:14pt"><span style="font-family:Times New Roman; -aw-import:ignore">&#xa0;</span></p><p style="color: #444444;margin-top:0pt; margin-bottom:0pt; line-height:115%; font-size:14pt"><span style="font-family:Times New Roman">Если Вы хотите разместить рекламный баннер на сайте GoodDeal, то вам необходимо написать нам сообщение на электронную почту </span><a href="mailto:office@gooddealonline.ru" style="text-decoration:none"><span style="font-family:Times New Roman; text-decoration:underline; color:#0000ff">office@gooddealonline.ru</span></a><span style="font-family:Times New Roman"> . Там Вы должны будете указать название</span><span style="font-family:Times New Roman; -aw-import:spaces">&#xa0; </span><span style="font-family:Times New Roman">организации и что будете рекламировать, а так же есть ли у Вас уже готовый баннер (размеры рекламного баннера: 300x500). Мы Вам ответим в ближайшее время и предложим наиболее удобные для Вас позиции.</span></p><p style="color: #444444;margin-top:0pt; margin-bottom:0pt; line-height:115%; font-size:14pt"><span style="font-family:Times New Roman; -aw-import:ignore">&#xa0;</span></p><p style="color: #444444;margin-top:0pt; margin-bottom:0pt; line-height:115%; font-size:14pt"><span style="font-family:Times New Roman">Обращаем Ваше внимание на то, что если Вы закажете размещение баннера сроком на месяц или меньше, разработка рекламного баннера будет платной.</span></p>',

  }
