export const enum ChatNotificationType {
  NEW_MESSAGE = 'NEW_MESSAGE',
  MARK_AS_READ = 'MARK_AS_READ',
  RESOLUTION_CHANGING_CANCEL = 'RESOLUTION_CHANGING_CANCEL',
  RESOLUTION_CHANGING_ACCEPT = 'RESOLUTION_CHANGING_ACCEPT',
  TASK_RESOLVED = 'TASK_RESOLVED'
}