export enum RateType {
  DISTANCE = 'DISTANCE',
  URGENTLY = 'URGENTLY',
  TRANSPORT_CATEGORY = 'TRANSPORT_CATEGORY',
  WEIGHT_CATEGORY = 'WEIGHT_CATEGORY',
  PRODUCT_CATEGORY = 'PRODUCT_CATEGORY',
  PORTER = 'PORTER',
  PASSENGER = 'PASSENGER',
  PERFORMER_ATTACHING = 'PERFORMER_ATTACHING'
}