export enum FilterStatusRequest {
    ALL = 'ALL',
    IN_PROGRESS = 'IN_PROGRESS',
    CUSTOMER_CONFITMED = 'CUSTOMER_CONFITMED',
    UNDER_CUNSIDERATION = 'UNDER_CUNSIDERATION',
    CANCELED = 'CANCELED'

}