export enum MapActions {
  CENTRE='CENTRE',
  ADD_POINT='ADD_POINT',
  ADD_START='ADD_START',
  ADD_END='ADD_END',
  DELETE='DELETE',
  DELETE_ALL='DELETE_ALL',
  ZOOM_IN='ZOOM_IN',
  ZOOM_OUT='ZOOM_OUT'
}
